# Generated by Django 5.1.5 on 2025-03-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
